name: IntelliJ Reformat Code

on:
  push:
    branches: [ main ]

jobs:
  reformat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: joutvhu/intellij-format@v1
        with:
          verify: true
          settings: .idea/codeStyles/Project.xml