name: IntelliJ Format

on:
  push:
    branches: ["main"]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'