name: IntelliJ Reformat Code

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  reformat:
    runs-on: ubuntu-latest
    name: IntelliJ
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check IntelliJ Formatting
        uses: sidhant92/intellij-format-action@v1
        with:
          tool_name: 'IntelliJ Diff'
          github_token: ${{ secrets.github_token }}
          path: '.'
          file_mask: '*.java'